version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - redis
    volumes:
      - ./:/var/www/html
  redis:
    image: redis
    ports:
      - "6379:6379"